# The cp commanad can take 3 forms:
#   1 ) cp [OPTION]... [-T] SOURCE DEST
#   2 ) cp [OPTION]... SOURCE... DIRECTORY
#   3 ) cp [OPTION]... -t DIRECTORY SOURCE...
#
# For each of these forms, the DEST or the DIRECTORY/basename(SOURCE) must
# simply be removed; howwever, the first two forms can be "safely" merged. The
# only real difference betweenthe two forms is whether o not DEST is a file or
# directory which is trivial to check in the command patten.


# cp [OPTION]... [-T] SOURCE DEST
# cp [OPTION]... SOURCE... DEST
[[entry]]
cmd = '''cp
    [-a --archive] [--atributes-only] [--backup[=CONTROL]] [-b] [--copy-contents] [-d] [-H] [-l --link]
    [-P --no-dereference] [-p] [--preserve=:,] [--no-preserve=:,] [--parents] [-R -r --recursive] [--sparse=WHEN]
    [--strip-trailing-slashes] [-v --verbose] [--one-file-system] [-Z] [--context=]

    [-f --force] [-u --update] [-i --interactive]

    [-T --no-target-directory] <SRC...> <DEST>'''
undo = 'rm % isdir($DEST) ? "`$DEST`/`basename($SRC)`" : $DEST %'

[[entry]]
cmd = '''cp
    [-a --archive] [--atributes-only] [--backup[=CONTROL]] [-b] [--copy-contents] [-d] [-H] [-l --link]
    [-P --no-dereference] [-p] [--preserve=:,] [--no-preserve=:,] [--parents] [-R -r --recursive] [--sparse=WHEN]
    [--strip-trailing-slashes] [-v --verbose] [--one-file-system] [-Z] [--context=]

    (![-n --no-clobber] [--remove-destination])

    [-T --no-target-directory] <SRC...> <DEST>'''
undo = 'rm % isdir($DEST) ? "`$DEST`/`basename($SRC)`" : $DEST %'
precise = true


# cp [OPTION]... -t DIRECTORY SOURCE>...
[[entry]]
cmd = '''cp
    [-a --archive] [--atributes-only] [--backup[=CONTROL]] [-b] [--copy-contents] [-d] [-H] [-l --link]
    [-P --no-dereference] [-p] [--preserve=:,] [--no-preserve=:,] [--parents] [-R -r --recursive] [--sparse=WHEN]
    [--strip-trailing-slashes] [-v --verbose] [--one-file-system] [-Z] [--context=]

    [-f --force] [-u --update] [-i --interactive]

    <-t --target-directory=> <SRC...>'''
undo = 'rm % "`$TARGET_DIRECTORY`/`basename($SRC)`" %'

[[entry]]
cmd = '''cp
    [-a --archive] [--atributes-only] [--backup[=CONTROL]] [-b] [--copy-contents] [-d] [-H] [-l --link]
    [-P --no-dereference] [-p] [--preserve=:,] [--no-preserve=:,] [--parents] [-R -r --recursive] [--sparse=WHEN]
    [--strip-trailing-slashes] [-v --verbose] [--one-file-system] [-Z] [--context=]

    (![-n --no-clobber] [--remove-destination])
    <-t --target-directory=> <SRC...>'''

undo = 'rm % "`$TARGET_DIRECTORY`/`basename($SRC)`" %'
precise = true