# The mkfifo command is very with one form 'mkdir [OPTION]... NAME...`. It
# can be undone by removing the created directories.
#
# Documentation: https://www.gnu.org/software/coreutils/mknod
[[entry]]
cmd = '''mknod
         [-m --mode=MODE] [-Z] [--context=CTX]

         <NAME> <TYPE>'''
undo = 'rm % $NAME... %'
precise = true

[[entry]]
cmd = '''mknod
         [-m --mode=MODE] [-Z] [--context=CTX]

         <NAME> <TYPE> <MAJOR> <MINOR>'''
undo = 'rm % $NAME... %'
precise = true