# The mv command can take generally 2 forms:
#   1 ) change the path of a file (renaming and moving to another directory)
#   2 ) moving multiple files into another directory
#
# Fortunately, both of these cases can be easily handled with a single undo
# expression, by checking if the DEST of the target command is a directory or
# not.
#
# If DEST is a directory, undo simply needs to move each of the SRC files back
# to their original path, and if DEST is a file you can do the same.

[[entry]]
cmd = '''mv
    [--backup=CONTROL] [-b] [-S --suffix=] [-v --verbose]

    [-f --force] [-i --interactive]

    <SRC...> <DST>'''
undo = 'mv % isdir($DST) ? "`$DST`/`basename($SRC)`" : $DST % % $SRC %'

[[entry]]
cmd = '''mv
    [--backup=CONTROL] [-b] [-S --suffix=] [-v --verbose]

    <-n --no-clobber>

    <SRC...> <DST>'''
undo = 'mv % isdir($DST) ? "`$DST`/`basename($SRC)`" : $DST % % $SRC %'
precise = true
