# The mv command can take generally 3 forms:
#   1 ) mv [OPTION]... [-T] SOURCE DEST
#   2 ) mv [OPTION]... SOURCE... DIRECTORY
#   3 ) mv [OPTION]... -t DIRECTORY SOURCE...
#
# Fortunately, all of these cases can be easily handled with a single undo
# expression, by checking if the DEST of the target command is a directory or
# not.
#
# If DEST is a directory, undo simply needs to move each of the SRC files back
# to their original path, and if DEST is a file you can do the same.
#
# Documentation: https://www.gnu.org/software/coreutils/mv


# mv [OPTION]... [-T] SOURCE DEST
# mv [OPTION]... SOURCE... DIRECTORY
[[entry]]
cmd = '''mv
         [--backup[=CONTROL]] [-b] [--strip-trailing-slashes] [-S --suffix=] [-Z --context]

         [-f --force] [-i --interactive] [-u --update]

         [-T --no-target-directory] <SRC...> <DST>'''
undo = 'mv % isdir($DST) ? "`$DST`/`basename($SRC)`" : $DST % % $SRC %'

[[entry]]
cmd = '''mv
         [--backup[=CONTROL]] [-b] [--strip-trailing-slashes] [-S --suffix=] [-Z --context]

         <-n --no-clobber>

         <SRC...> <DST>'''
undo = 'mv % isdir($DST) ? "`$DST`/`basename($SRC)`" : $DST % % $SRC %'
precise = true


# mv [OPTION]... -t DIRECTORY SOURCE...
[[entry]]
cmd = '''mv
         [--backup[=CONTROL]] [-b] [--strip-trailing-slashes] [-S --suffix=] [-Z --context]

         [-f --force] [-i --interactive] [-u --update]

         <-t --target-directory=> <SRC...>'''
undo = 'mv % "`$TARGET_DIRECTORY`/`basename($SRC)`" % % $SRC %'

[[entry]]
cmd = '''mv
         [--backup[=CONTROL]] [-b] [--strip-trailing-slashes] [-S --suffix=] [-Z --context]

         <-n --no-clobber>

         <-t --target-directory=> <SRC...>'''
undo = 'mv % "`$TARGET_DIRECTORY`/`basename($SRC)`" % % $SRC %'
precise = true
